<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>Aptabase.Core</PackageId>
        <Version>0.2.3</Version>
        <AssemblyVersion>$(Version)</AssemblyVersion>
        <FileVersion>$(Version)</FileVersion>
        <TargetFramework>net8.0</TargetFramework>
        <Description>Dotnet SDK for Aptabase: Open Source, Privacy-First and Simple Analytics for Mobile, Desktop and Web Apps</Description>
        <Authors>Aptabase Team</Authors>
        <Company>Aptabase</Company>
        <PackageProjectUrl>https://aptabase.com</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>logo.png</PackageIcon>
        <RepositoryUrl>https://github.com/aptabase/aptabase-dotnet</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>analytics, privacy, dotnet, sdk, telemetry</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\..\etc\logo.png" Pack="true" PackagePath="\" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="DotNext.Threading" Version="5.2.0" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    </ItemGroup>
</Project>
